### ISSUE TITLE
'Future<bool?>' is not a subtype of type 'FutureOr<bool>' in type cast

### ISSUE THREAD

**Issue by guccisekspir** [natintosh/intl_phone_number_input#203]
**Describe the bug**
When I try to click phone field I get this error after writing anything  -> [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Future<bool?>' is not a subtype of type 'FutureOr<bool>' in type cast

`E/flutter ( 7313): #2      _InputWidgetState.onChanged
package:intl_phone_number_input/…/widgets/input_widget.dart:312
E/flutter ( 7313): #3      new TextFormField.<anonymous closure>.onChangedHandler
package:flutter/…/material/text_form_field.dart:246
E/flutter ( 7313): #4      EditableTextState._formatAndSetValue
package:flutter/…/widgets/editable_text.dart:2276
E/flutter ( 7313): #5      EditableTextState.updateEditingValue
package:flutter/…/widgets/editable_text.dart:1731
E/flutter ( 7313): #6      TextInput._handleTextInputInvocation
package:flutter/…/services/text_input.dart:1279
E/flutter ( 7313): #7      MethodChannel._handleAsMethodCall
package:flutter/…/services/platform_channel.dart:435
E/flutter ( 7313): #8      MethodChannel.setMethodCallHandler.<anonymous closure>
package:flutter/…/services/platform_channel.dart:382
E/flutter ( 7313): #9      _DefaultBinaryMessenger.handlePlatformMessage
package:flutter/…/services/binding.dart:284
E/flutter ( 7313): #10     _invoke3.<anonymous closure> (dart:ui/hooks.dart:221:15)
`

**Package version**
0.7.0

** Targeted platforms (please complete the following information):**
 - Android

**Comment by HasanAlyazidi** [comment]
Same error `v0.7.0`

**Comment by natintosh** [comment]
Hi, I just pushed a fix. Could you help me check if it resolves this issue? Thanks.

```yaml
  intl_phone_number_input:
    git:
      url:https://github.com/natintosh/intl_phone_number_input
      ref: b1dd083e58987e61a74242313fe587ffc20be7cc
```

**Comment by sarbogast** [comment]
I'm seeing the same error. And with your fix, I don't see the error in the console anymore, but I still get a PlatformException on NOT_A_NUMBER that stops my debugger.

**Comment by sarbogast** [comment]
This fix seems to work
