### ISSUE TITLE
Error caused by setState()

### ISSUE THREAD

**Issue by b02505048** [natintosh/intl_phone_number_input#60]
I'm using `onInputValidated()` to check whether should we enable the NEXT BUTTON.

```
...
   Stack(
     children: <Widget>[
          InternationalPhoneNumberInput(
                onInputChanged: (PhoneNumber number) {
                  this.number = number;
                },
                onInputValidated: (bool value) {
                  setState(() {
                      _isValid = value;
                  });
                },
                ignoreBlank: false,
                autoValidate: false,
                initialValue: number,
                textFieldController: controller,
                ...
         ),
         Opacity(
                opacity: _isValid ? 1.0 : 0.5,
                child: FlatButton( onPressed: () {...}, child: Text('Next') )
         ),
     ]
  )
...
```

And will get the error below 
`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(NumberParseException, The string supplied did not seem to be a phone number., null)`

**Comment by natintosh** [comment]
@b02505048  thanks for raising this issue. I have been unable to reproduce this issue, but the cause of this is an external dependency that throws an exception when this is not true

```java
if (!isViablePhoneNumber(nationalNumber)) {
      throw new NumberParseException(NumberParseException.ErrorType.NOT_A_NUMBER,
          "The string supplied did not seem to be a phone number.");
    }
```


```java
  /**
   * Checks to see if the string of characters could possibly be a phone number at all. At the
   * moment, checks to see that the string begins with at least 2 digits, ignoring any punctuation
   * commonly found in phone numbers.
   * This method does not require the number to be normalized in advance - but does assume that
   * leading non-number symbols have been removed, such as by the method extractPossibleNumber.
   *
   * @param number  string to be checked for viability as a phone number
   * @return  true if the number could be a phone number of some sort, otherwise false
   */
  // @VisibleForTesting
  static boolean isViablePhoneNumber(CharSequence number) {
    if (number.length() < MIN_LENGTH_FOR_NSN) {
      return false;
    }
    Matcher m = VALID_PHONE_NUMBER_PATTERN.matcher(number);
    return m.matches();
  }
```

**Comment by b02505048** [comment]
@natintosh Thanks for replying. Could we do the phone number validation outside the `InternationalPhoneNumberInput`? 

I think this error message would occur when the user is typing the first digit number since `isViablePhoneNumber` function must have at least 2 digits?

**Comment by natintosh** [comment]
Thanks for suggesting this, I will consider it for the next major update, but its chances are low.

**Comment by ISimplifyComplexity** [comment]
@natintosh I see a similar error when I set autovalidate to true:


           InternationalPhoneNumberInput(
                        countries: ["GB"],
                        initialValue: initialPhoneNumber,
                        ignoreBlank: true,
                        autoValidate: true,
                        textFieldController: controller,
                        inputBorder: OutlineInputBorder(),
                        selectorType: PhoneInputSelectorType.BOTTOM_SHEET,
                      ),


I get an error saying setState() or markNeedsBuild called during build... 

if I turn autovalidate off then I don't see the error?!

**Comment by natintosh** [comment]
Hi @ISimplifyComplexity I published a fixed to this issue thanks for bringing this up

**Comment by marcomartinscastanho** [comment]
Hello, I'm still having an issue with setState() inside onInputValidated().

When I tap the input area (to open the keyboard), I get this
```
W/IInputConnectionWrapper(24974): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(24974): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(24974): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(24974): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(24974): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(24974): getTextAfterCursor on inactive InputConnection
```
Then when I type a 0 I get this
```
I/flutter (24974): +330
E/flutter (24974): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(NumberParseException, The string supplied is too short to be a phone number., null)
E/flutter (24974): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (24974): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (24974): <asynchronous suspension>
E/flutter (24974): #2      PhoneNumberUtil.getRegionInfo (package:libphonenumber/libphonenumber.dart:61:51)
E/flutter (24974): #3      PhoneNumber.getRegionInfoFromPhoneNumber (package:intl_phone_number_input/src/utils/phone_number.dart:41:51)
E/flutter (24974): #4      PhoneNumber.getParsableNumber (package:intl_phone_number_input/src/utils/phone_number.dart:60:34)
E/flutter (24974): #5      _InputWidgetState.initialiseWidget (package:intl_phone_number_input/src/widgets/input_widget.dart:262:31)
E/flutter (24974): #6      _InputWidgetState.didUpdateWidget (package:intl_phone_number_input/src/widgets/input_widget.dart:251:7)
E/flutter (24974): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4396:58)
E/flutter (24974): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (24974): #9      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
E/flutter (24974): #10     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
E/flutter (24974): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (24974): #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter (24974): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (24974): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (24974): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (24974): #16     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
E/flutter (24974): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (24974): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (24974): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (24974): #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
E/flutter (24974): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (24974): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (24974): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (24974): #24     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
E/flutter (24974): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (24974): #26     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
E/flutter (24974): #27     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
E/flutter (24974): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (24974): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (24974): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (24974): #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
E/flutter (24974): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (24974): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (24974): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (24974): #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
E/flutter (24974): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (24974): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (24974): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (24974): #39     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
E/flutter (24974): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (24974): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter (24974): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter (24974): #43     ComponentElement.performRebuild (package:flutter/src/widge
```
And if then I type any other number, onInputChange() goes into infinite loop and I can't type anything else anymore.

I'm using version ^0.4.6+2, which I think is the version that includes the fix to the original issue of this topic.
